#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
SDL_FILE="sdl.csp"
COPYRIGHT="#[
  Simple DirectMedia Layer
  Copyright (C) 1997-2022 Sam Lantinga <slouken@libsdl.org>

  This software is provided 'as-is', without any express or implied
  warranty.  In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
     claim that you wrote the original software. If you use this software
     in a product, an acknowledgment in the product documentation would be
     appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
     misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.

    ** THIS FILE GETS AUTOMATICALLY GENERATED BY \`sdl2/generate.sh\`!
]#

[link(\"pthread\", \"SDL2\")]
"

CODE="

macro SDL_INIT_TIMER          { (0x00000001: u32) }
macro SDL_INIT_AUDIO          { (0x00000010: u32) }
macro SDL_INIT_VIDEO          { (0x00000020: u32) }
macro SDL_INIT_JOYSTICK       { (0x00000200: u32) }
macro SDL_INIT_HAPTIC         { (0x00001000: u32) }
macro SDL_INIT_GAMECONTROLLER { (0x00002000: u32) }
macro SDL_INIT_EVENTS         { (0x00004000: u32) }
macro SDL_INIT_SENSOR         { (0x00008000: u32) }
macro SDL_INIT_NOPARACHUTE    { (0x00100000: u32) }

macro SDL_INIT_EVERYTHING     {
    SDL_INIT_TIMER! |
    SDL_INIT_AUDIO! |
    SDL_INIT_VIDEO! |
    SDL_INIT_JOYSTICK! |
    SDL_INIT_HAPTIC! |
    SDL_INIT_GAMECONTROLLER! |
    SDL_INIT_EVENTS! |
    SDL_INIT_SENSOR! |
    SDL_INIT_NOPARACHUTE!
}

namespace sdl {
    extern \"C\" {
        fn SDL_Init(flags: u32): i32;
        fn SDL_InitSubSystem(flags: u32): i32;
        fn SDL_WasInit(flags: u32): u32;
        fn SDL_Quit();
    }
}
"

pushd $SCRIPT_DIR

gen-allimport-file $SDL_FILE $SCRIPT_DIR "Main include header for the SDL library"

echo "$COPYRIGHT$(cat $SDL_FILE)$CODE" > $SDL_FILE

popd