#ifndef CSPYDR_TOKEN_H
#define CSPYDR_TOKEN_H

#include "io/file.h"
#include "config.h"
#include "../../api/include/cspydr.h"

#define TOKEN_ID CSPYDR_TOKEN_ID
#define TOKEN_MACRO_CALL CSPYDR_TOKEN_MACRO_CALL
#define TOKEN_INFIX_CALL CSPYDR_TOKEN_INFIX_CALL
#define TOKEN_INT CSPYDR_TOKEN_INT
#define TOKEN_FLOAT CSPYDR_TOKEN_FLOAT
#define TOKEN_CHAR CSPYDR_TOKEN_CHAR
#define TOKEN_STRING CSPYDR_TOKEN_STRING
#define TOKEN_TRUE CSPYDR_TOKEN_TRUE
#define TOKEN_FALSE CSPYDR_TOKEN_FALSE
#define TOKEN_NIL CSPYDR_TOKEN_NIL
#define TOKEN_LPAREN CSPYDR_TOKEN_LPAREN
#define TOKEN_RPAREN CSPYDR_TOKEN_RPAREN
#define TOKEN_LBRACE CSPYDR_TOKEN_LBRACE
#define TOKEN_RBRACE CSPYDR_TOKEN_RBRACE
#define TOKEN_LBRACKET CSPYDR_TOKEN_LBRACKET
#define TOKEN_RBRACKET CSPYDR_TOKEN_RBRACKET
#define TOKEN_GT CSPYDR_TOKEN_GT
#define TOKEN_LT CSPYDR_TOKEN_LT
#define TOKEN_EQ CSPYDR_TOKEN_EQ
#define TOKEN_NOT_EQ CSPYDR_TOKEN_NOT_EQ
#define TOKEN_GT_EQ CSPYDR_TOKEN_GT_EQ
#define TOKEN_LT_EQ CSPYDR_TOKEN_LT_EQ
#define TOKEN_BANG CSPYDR_TOKEN_BANG
#define TOKEN_PLUS CSPYDR_TOKEN_PLUS
#define TOKEN_MINUS CSPYDR_TOKEN_MINUS
#define TOKEN_STAR CSPYDR_TOKEN_STAR
#define TOKEN_SLASH CSPYDR_TOKEN_SLASH
#define TOKEN_PERCENT CSPYDR_TOKEN_PERCENT
#define TOKEN_ARROW CSPYDR_TOKEN_ARROW
#define TOKEN_AND CSPYDR_TOKEN_AND
#define TOKEN_OR CSPYDR_TOKEN_OR
#define TOKEN_BIT_OR CSPYDR_TOKEN_BIT_OR
#define TOKEN_PIPE CSPYDR_TOKEN_PIPE
#define TOKEN_REF CSPYDR_TOKEN_REF
#define TOKEN_TILDE CSPYDR_TOKEN_TILDE
#define TOKEN_VA_LIST CSPYDR_TOKEN_VA_LIST
#define TOKEN_INC CSPYDR_TOKEN_INC
#define TOKEN_DEC CSPYDR_TOKEN_DEC
#define TOKEN_ASSIGN CSPYDR_TOKEN_ASSIGN
#define TOKEN_ADD CSPYDR_TOKEN_ADD
#define TOKEN_SUB CSPYDR_TOKEN_SUB
#define TOKEN_MULT CSPYDR_TOKEN_MULT
#define TOKEN_DIV CSPYDR_TOKEN_DIV
#define TOKEN_MOD CSPYDR_TOKEN_MOD
#define TOKEN_XOR CSPYDR_TOKEN_XOR
#define TOKEN_XOR_ASSIGN CSPYDR_TOKEN_XOR_ASSIGN
#define TOKEN_LSHIFT CSPYDR_TOKEN_LSHIFT
#define TOKEN_RSHIFT CSPYDR_TOKEN_RSHIFT
#define TOKEN_LSHIFT_ASSIGN CSPYDR_TOKEN_LSHIFT_ASSIGN
#define TOKEN_RSHIFT_ASSIGN CSPYDR_TOKEN_RSHIFT_ASSIGN
#define TOKEN_BIT_AND_ASSIGN CSPYDR_TOKEN_BIT_AND_ASSIGN
#define TOKEN_BIT_OR_ASSIGN CSPYDR_TOKEN_BIT_OR_ASSIGN
#define TOKEN_COLON CSPYDR_TOKEN_COLON
#define TOKEN_COMMA CSPYDR_TOKEN_COMMA
#define TOKEN_DOT CSPYDR_TOKEN_DOT
#define TOKEN_SEMICOLON CSPYDR_TOKEN_SEMICOLON
#define TOKEN_UNDERSCORE CSPYDR_TOKEN_UNDERSCORE
#define TOKEN_DOLLAR CSPYDR_TOKEN_DOLLAR
#define TOKEN_STATIC_MEMBER CSPYDR_TOKEN_STATIC_MEMBER
#define TOKEN_POW_2 CSPYDR_TOKEN_POW_2
#define TOKEN_POW_3 CSPYDR_TOKEN_POW_3
#define TOKEN_C_ARRAY CSPYDR_TOKEN_C_ARRAY
#define TOKEN_IF CSPYDR_TOKEN_IF
#define TOKEN_ELSE CSPYDR_TOKEN_ELSE
#define TOKEN_LOOP CSPYDR_TOKEN_LOOP
#define TOKEN_RETURN CSPYDR_TOKEN_RETURN
#define TOKEN_MATCH CSPYDR_TOKEN_MATCH
#define TOKEN_FN CSPYDR_TOKEN_FN
#define TOKEN_LET CSPYDR_TOKEN_LET
#define TOKEN_TYPE CSPYDR_TOKEN_TYPE
#define TOKEN_STRUCT CSPYDR_TOKEN_STRUCT
#define TOKEN_UNION CSPYDR_TOKEN_UNION
#define TOKEN_ENUM CSPYDR_TOKEN_ENUM
#define TOKEN_IMPORT CSPYDR_TOKEN_IMPORT
#define TOKEN_EXTERN CSPYDR_TOKEN_EXTERN
#define TOKEN_MACRO CSPYDR_TOKEN_MACRO
#define TOKEN_CONST CSPYDR_TOKEN_CONST
#define TOKEN_NAMESPACE CSPYDR_TOKEN_NAMESPACE
#define TOKEN_SIZEOF CSPYDR_TOKEN_SIZEOF
#define TOKEN_TYPEOF CSPYDR_TOKEN_TYPEOF
#define TOKEN_ALIGNOF CSPYDR_TOKEN_ALIGNOF
#define TOKEN_WHILE CSPYDR_TOKEN_WHILE
#define TOKEN_FOR CSPYDR_TOKEN_FOR
#define TOKEN_CONTINUE CSPYDR_TOKEN_CONTINUE
#define TOKEN_BREAK CSPYDR_TOKEN_BREAK
#define TOKEN_NOOP CSPYDR_TOKEN_NOOP
#define TOKEN_LEN CSPYDR_TOKEN_LEN
#define TOKEN_ASM CSPYDR_TOKEN_ASM
#define TOKEN_USING CSPYDR_TOKEN_USING
#define TOKEN_WITH CSPYDR_TOKEN_WITH
#define TOKEN_DO CSPYDR_TOKEN_DO
#define TOKEN_UNLESS CSPYDR_TOKEN_UNLESS
#define TOKEN_CURRENT_FN CSPYDR_TOKEN_CURRENT_FN
#define TOKEN_BUILTIN_REG_CLASS CSPYDR_TOKEN_BUILTIN_REG_CLASS
#define TOKEN_BUILTIN_IS_INT CSPYDR_TOKEN_BUILTIN_IS_INT
#define TOKEN_BUILTIN_IS_UINT CSPYDR_TOKEN_BUILTIN_IS_UINT
#define TOKEN_BUILTIN_IS_FLOAT CSPYDR_TOKEN_BUILTIN_IS_FLOAT
#define TOKEN_BUILTIN_IS_POINTER CSPYDR_TOKEN_BUILTIN_IS_POINTER
#define TOKEN_BUILTIN_IS_ARRAY CSPYDR_TOKEN_BUILTIN_IS_ARRAY
#define TOKEN_BUILTIN_IS_STRUCT CSPYDR_TOKEN_BUILTIN_IS_STRUCT
#define TOKEN_BUILTIN_IS_UNION CSPYDR_TOKEN_BUILTIN_IS_UNION
#define TOKEN_BUILTIN_TO_STR CSPYDR_TOKEN_BUILTIN_TO_STR
#define TOKEN_ERROR CSPYDR_TOKEN_ERROR
#define TOKEN_EOF CSPYDR_TOKEN_EOF

typedef enum CSPYDR_TOKEN_TYPE TokenType_T;

typedef struct CSPYDR_TOKEN_STRUCT {
    u32 line;
    u32 pos;
    TokenType_T type;

    File_T* source;

    char value[];
} __attribute__((packed)) Token_T;

Token_T* init_token(char* value, u32 line, u32 position, TokenType_T type, File_T* source);
char* token_to_str(Token_T* token);

#endif