#!/usr/bin/env bash

# a small script for installing the nvim extension

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR

if [[ -d "$HOME/.config/nvim" ]];
then
    NVIM_CONFIG_DIR="$HOME/.config/nvim"
elif [[ -d "$HOME/.nvim" ]];
then
    NVIM_CONFIG_DIR="$HOME/.nvim"
else
    echo "Error: Unable to find NeoVim configuration path in $HOME!"
fi

set -xe

mkdir -p $NVIM_CONFIG_DIR/lua
cp cspydr.lua $NVIM_CONFIG_DIR/lua/cspydr.lua
cp -r syntax/* $NVIM_CONFIG_DIR/syntax

PACKAGE_INIT_STMT="\n-- auto-generated by \`install.sh\`\nrequire('cspydr').setup()"

if ! [[ -f "$NVIM_CONFIG_DIR/init.lua" ]];
then
    echo "Error: Unable to find init.lua in $NVIM_CONFIG_DIR."
    echo "please paste the following lua code into your configuratgion files in order to activate the cspydr package:"
    echo "    $PACKAGE_INIT_STMT"
    exit 0
fi

if grep -q "require('cspydr')" "$NVIM_CONFIG_DIR/init.lua" || grep -q "require(\"cspydr\")" "$NVIM_CONFIG_DIR/init.lua";
then
    echo "Note: Plugin already activated"
else
    echo -e $PACKAGE_INIT_STMT >> $NVIM_CONFIG_DIR/init.lua
fi

echo "CSpydr NeoVim plugin successfully installed!"
