#include "../backend.h"

#include "codegen/codegen.h"
#include "platform/linux/linux_platform.h"
#include "io/log.h"

static void C99_begin_file(CodegenData_T* c)
{
    codegen_println(c, "// generated by cspc - The CSpydr Programming Language Compiler.");
    codegen_println(c, "int main() { return 0; }");
}

static void C99_finish_file(CodegenData_T* c)
{

}

static void C99_compile(CodegenData_T* c, const char* input_file, const char* output_file)
{
    List_T* args = init_list(); 

    list_push(args, c->context->cc);
    list_push(args, "-c");
    list_push(args, (void*) input_file);
    list_push(args, "-std=c99");
    list_push(args, "-o");
    list_push(args, (void*) output_file);

    if(c->generate_debug_info)
        list_push(args, "-g");

    for(size_t i = 0; i < c->context->compiler_flags->size; i++)
        list_push(args, c->context->compiler_flags->items[i]);

    if(c->context->flags.optimize)
        list_push(args, "-O2"); // -O3 is known to cause issues

    list_push(args, NULL);

    i32 exit_code = subprocess(args->items[0], (char* const*) args->items, false);
    free_list(args);

    if(exit_code != 0)
    {
        LOG_ERROR_F(COLOR_BOLD_RED "[Error]" COLOR_RESET COLOR_RED "C compiler terminated with non-zero exit code %d.\n" COLOR_RESET, exit_code);
        throw(c->context->main_error_exception);
    }
}

BACKEND_CALLBACKS_IMPL(C99);
