#include "codegen/backend.h"

#include "codegen/codegen.h"
#include "io/log.h"
#include "ir/ir.h"
#include "platform/linux/linux_platform.h"

#include <assert.h>

#define P_ln(...) codegen_println(c, __VA_ARGS__)

static void X86_64_GAS_begin_file(CodegenData_T* c)
{
    P_ln("// Generated by cspc - The CSpydr Programming Language Compiler");
}

static void X86_64_GAS_finish_file(CodegenData_T* c)
{
    P_ln(".section .text");
    P_ln(".globl main");
    P_ln("main:");
    P_ln("  mov $69, %rax");
    P_ln("  ret");

    P_ln(".section .note.GNU-stack");
    P_ln(".byte 0");
}

static void X86_64_GAS_generate_ir(CodegenData_T* c, IR_T* ir)
{
    assert(false && "unimplemented");
}

static void X86_64_GAS_compile(CodegenData_T* c, const char* input_file, const char* output_file)
{
    List_T* args = init_list();

    list_push(args, c->context->as);
    list_push(args, "-c");
    list_push(args, (void*) input_file);
    list_push(args, "-o");
    list_push(args, (void*) output_file);

    if(c->generate_debug_info)
        list_push(args, "-g");

    for(size_t i = 0; i < c->context->compiler_flags->size; i++)
        list_push(args, c->context->compiler_flags->items[i]);

    if(c->context->flags.optimize)
        list_push(args, "-O2"); // -O3 is known to cause issues

    list_push(args, NULL);

    i32 exit_code = subprocess(args->items[0], (char* const*) args->items, false);
    free_list(args);

    if(exit_code != 0)
    {
        LOG_ERROR_F(COLOR_BOLD_RED "[Error]" COLOR_RESET COLOR_RED " Assembler terminated with non-zero exit code: %d.\n", exit_code);
        throw(c->context->main_error_exception);
    }
}

BACKEND_CALLBACKS_IMPL(X86_64_GAS);
